[network]
name = "mainnet"
node_rpc_address = "https://stacks-node-api.mainnet.stacks.co"
deployment_fee_rate = 10

[accounts.deployer]
# Use your own mnemonic for mainnet deployment
# mnemonic = "your mainnet mnemonic here"
